### ISSUE TITLE
Right Overflowed by 142 Pixels

### ISSUE THREAD

**Issue by Divjot121** [Divjot121/SOS-WEATHER#1]
Please Fix out this issue with testing and right approach
thanks

**Comment by janu-rangde** [comment]
add .toStringAsFixed(2) with temp.
 like this
`"${(state.weather.temperature!.celsius! - 3).clamp(-30, 50).toStringAsFixed(2)} °C"`

**Comment by janugandhi** [comment]
add .toStringAsFixed(2) with temp.
like this
`"${(state.weather.temperature!.celsius! - 3).clamp(-30, 50).toStringAsFixed(2)} °C"`
